FROM ubuntu:19.04
WORKDIR /app

# Install node.js
RUN apt-get update -qq && \
  apt-get install -qq curl && \
  curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
  apt-get install -y nodejs

# Add source files
ADD compositor compositor
ADD protocol protocol

# Enter application directory
WORKDIR /app/compositor

# Build source
RUN npm install && \
  npm run prepare

# Start server
CMD npm run start
